# Generated by Django 3.1.2 on 2020-11-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0003_auto_20201103_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=40)),
                ('package', models.CharField(max_length=20)),
                ('last_date_apply', models.DateField()),
                ('location', models.CharField(max_length=15)),
                ('no_of_vacancies', models.IntegerField(default=1)),
                ('type_of_branch', models.CharField(max_length=10)),
                ('no_of_applications', models.IntegerField()),
                ('al_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.alumni')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.company')),
            ],
            options={
                'unique_together': {('job_id', 'company_id')},
            },
        ),
        migrations.CreateModel(
            name='Applied_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_applied', models.DateField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.vacancies')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.student')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=15)),
                ('Type', models.CharField(max_length=15)),
                ('Date_of_event', models.DateField()),
                ('time', models.TimeField()),
                ('contact_no', models.CharField(max_length=12)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.student')),
            ],
        ),
    ]
