# Generated by Django 3.1.2 on 2020-11-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_vacancies_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='no_of_applications',
            field=models.IntegerField(default=0),
        ),
    ]
