# Generated by Django 3.1.2 on 2020-10-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch_hod', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=14)),
                ('mail_id', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=100)),
                ('type', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('no_of_alumni', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('year_of_grad', models.IntegerField(default=2018, max_length=4)),
                ('work_expirience', models.IntegerField(default=2, max_length=2)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.branch')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.company')),
            ],
        ),
    ]
