# Generated by Django 3.1.2 on 2020-11-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Login', '0002_auto_20201023_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='mail_id',
            field=models.EmailField(default='@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='branch',
            name='mail_id',
            field=models.EmailField(default='@gamil.com', max_length=30),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('year_of_grad', models.IntegerField(default=2018)),
                ('mail_id', models.EmailField(default='@gmail.com', max_length=30)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.branch')),
            ],
        ),
    ]
